### PR TITLE
Add proxy aggregator tests

### PR DESCRIPTION
**Pull request by mrbarge**
This addresses the PR comments of #67 by assessing the GaugeVec returned by the metrics aggregator against expected results.

Comparing against the string representation as returned by `CollectAndCompare` is an approach shared by several other OCP codebase tests and is the few (and simplest) ways of doing this that the prometheus client_golang will actually let us do.

### CODE REVIEW

**Comment by mrbarge** [comment]
cc @T0MASD @arjunrn if you could please review and - if happy - merge into the OSD-8061 branch and then accordingly please review PR #67 to see if that can be merged given the addition of these tests. Thanks!

**Comment by jharrington22** [comment]
@mrbarge @T0MASD I'll review this by tomorrow.

**Pull request merged**
